// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmDC1xSbQFyiLGrmuF3UJeXSkqR5CzxrI',
    appId: '1:137158026645:web:5a004d7b5fa9b4a959429c',
    messagingSenderId: '137158026645',
    projectId: 'flutter-firebase-a2677',
    authDomain: 'flutter-firebase-a2677.firebaseapp.com',
    storageBucket: 'flutter-firebase-a2677.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0y8At-0oOKiDSKc7PcGpU7pkOEFChmEo',
    appId: '1:137158026645:android:f20f7f12a3d9686759429c',
    messagingSenderId: '137158026645',
    projectId: 'flutter-firebase-a2677',
    storageBucket: 'flutter-firebase-a2677.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7sfpWKIGqJ8Z7oZ2GPpwFs7Z6NeXKJH8',
    appId: '1:137158026645:ios:86c1ad8731ff351459429c',
    messagingSenderId: '137158026645',
    projectId: 'flutter-firebase-a2677',
    storageBucket: 'flutter-firebase-a2677.appspot.com',
    iosClientId: '137158026645-1a3860e5nauvbp884c8c6jl11ctg38kf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7sfpWKIGqJ8Z7oZ2GPpwFs7Z6NeXKJH8',
    appId: '1:137158026645:ios:86c1ad8731ff351459429c',
    messagingSenderId: '137158026645',
    projectId: 'flutter-firebase-a2677',
    storageBucket: 'flutter-firebase-a2677.appspot.com',
    iosClientId: '137158026645-1a3860e5nauvbp884c8c6jl11ctg38kf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
